# 为`cargo build`命令设置默认的目标平台。
# 现在，执行`cargo build`就相当于执行`cargo build --target riscv64gc-unknown-none-elf`。
#
# riskv64gc-unknown-none-elf的含义
# - riscv64gc: RISC-V 64位GC扩展
# - unknown: 未知的供应商
# - none: 不使用操作系统
# - elf: 使用ELF格式的输出文件
[build]
target = "riscv64gc-unknown-none-elf"
