# 为`cargo build`命令设置默认的目标平台。
# 现在，执行`cargo build`就相当于执行`cargo build --target riscv64gc-unknown-none-elf`。
#
# riskv64gc-unknown-none-elf的含义
# - riscv64gc: RISC-V 64位GC扩展
# - unknown: 未知的供应商
# - none: 不使用操作系统
# - elf: 使用ELF格式的输出文件
[build]
target = "riscv64gc-unknown-none-elf"


# 为默认目标平台设置编译选项。在编译时，这些参数会传递给rustc。
[target.riscv64gc-unknown-none-elf]
rustflags = [
    # 使用链接脚本src/linker.ld。该脚本用于定义程序的内存布局等。
    "-Clink-arg=-Tsrc/linker.ld",
    # 避免栈帧指针（fp寄存器）被编译器优化，方便调试。
    "-Cforce-frame-pointers=yes",
]
